[pytest]
testpaths =
    starlake-orchestration/src/test/python
    starlake-airflow/src/test/python
    starlake-dagster/src/test/python
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -ra -q --import-mode=importlib
