name: Build & Deploy Maven for root module

on:
  workflow_dispatch:

env:
  JAVA_VERSION: 17
  PYTHON_VERSION: 3.11
  MAVEN_OPTS: -Xmx1G

jobs:
  deploy-artefacts:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Configure Java + Maven
      - name: Set up Java and Maven
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ env.JAVA_VERSION }}
          cache: maven
          server-id: ossrh
          server-username: __token__
          server-password: ${{ secrets.SONATYPE_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}

      # Check Maven settings
      - name: Verify Maven settings
        run: mvn help:effective-settings

      # 3️⃣ Jar Deployment
      - name: Deploy Orchestration
        run: |
          PROFILE=release
          echo "Activating Maven profile: $PROFILE for root module"
          mvn --non-recursive deploy -P $PROFILE
